runtime: nodejs10
env_variables:
  GCS_BUCKET: wiadro13121
  GCLOUD_PROJECT: salongierpc
  GCS_KEYFILE: ./config.json
  MJ_APIKEY_PUBLIC: KEY
  MJ_APIKEY_PRIVATE: KEY
handlers:
- url: /.*
  script: auto
  secure: always
